### ISSUE TITLE
When an uppercase letter is set as the new project name, the application throws a difficult to read error

### ISSUE THREAD

**Issue by adrian-lorenzo** [boostercloud/booster#1195]
# Bug Report

## Current Behavior

If we create a project and set a name with uppercase letters, like with the following command:

We obtain the following output that includes a trace:

```
computer@someoneComputer projects % boost new:project UppercaseApplication
UppercaseApplication: Project name cannot contain uppercase letters:

    Found: 'UppercaseApplication'
    at assertNameIsCorrect (/.nvm/versions/node/v16.17.0/lib/node_modules/@boostercloud/cli/dist/services/provider-service.js:16:15)
    at Project.run (/.nvm/versions/node/v16.17.0/lib/node_modules/@boostercloud/cli/dist/commands/new/project.js:18:56)
    at Project._run (/.nvm/versions/node/v16.17.0/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/command.js:43:31) {
  restrictionText: 'contain uppercase letters'
}
```

## Expected behavior

To obtain a human readable message, without a trace.

```
Error ⚠️: Your Booster project name cannot contain uppercase letters. You choose "UppercaseApplication"
```

### Environment

- Booster version: [e.g. 0.15.1] 0.30.7

**Comment by fseda** [comment]
Is this issue open?
