### ISSUE TITLE
Required packages rimraf and tmsc not found while running boost deploy command

### ISSUE THREAD

**Issue by mnlx** [boostercloud/booster#1378]
# Bug Report

## Current Behavior

I'm following the booster framework getting started tutorial and running on a barebones newly deployed system. Everything is working as expected, except when I get to part 6.2 and run the command: `boost deploy -e production` which returns the following error:

```sh
[2023-03-15T14:09:29.295Z] boost deploy -e production
[2023-03-15T14:09:29.295Z] Error: [38;2;250;110;89m[ChildProcessError] Project contains compilation errors:[39m
[2023-03-15T14:09:29.295Z] Command failed: npm run clean
[2023-03-15T14:09:29.295Z] sh: 1: rimraf: not found
[2023-03-15T14:09:29.295Z] npm ERR! code ELIFECYCLE
[2023-03-15T14:09:29.295Z] npm ERR! syscall spawn
[2023-03-15T14:09:29.295Z] npm ERR! file sh
[2023-03-15T14:09:29.295Z] npm ERR! errno ENOENT
[2023-03-15T14:09:29.295Z] npm ERR! boosted-blog@0.1.0 clean: `rimraf ./dist tsconfig.tsbuildinfo`
[2023-03-15T14:09:29.295Z] npm ERR! spawn ENOENT
[2023-03-15T14:09:29.295Z] npm ERR! 
[2023-03-15T14:09:29.295Z] npm ERR! Failed at the boosted-blog@0.1.0 clean script.
[2023-03-15T14:09:29.295Z] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2023-03-15T14:09:29.295Z] 
[2023-03-15T14:09:29.295Z] npm ERR! A complete log of this run can be found in:
[2023-03-15T14:09:29.295Z] npm ERR!     /home/mo/.npm/_logs/2023-03-15T14_09_29_279Z-debug.log
[2023-03-15T14:09:29.295Z]  `npm run clean` (exited with error code 1)
[2023-03-15T14:09:29.295Z]     at /usr/lib/node_modules/@boostercloud/cli/dist/common/errors.js:18:12
[2023-03-15T14:09:29.295Z]     at /usr/lib/node_modules/@boostercloud/cli/node_modules/@effect-ts/system/Effect/orDieWith.js:33:56
[2023-03-15T14:09:29.295Z]     at Object.fold_ (/usr/lib/node_modules/@boostercloud/cli/node_modules/@effect-ts/system/Either/core.js:417:23)
[2023-03-15T14:09:29.295Z]     at HandlerFrame.apply (/usr/lib/node_modules/@boostercloud/cli/node_modules/@effect-ts/system/Effect/foldM.js:33:52)
[2023-03-15T14:09:29.295Z]     at FiberContext.nextInstr (/usr/lib/node_modules/@boostercloud/cli/node_modules/@effect-ts/system/Fiber/context.js:391:16)
[2023-03-15T14:09:29.295Z]     at FiberContext.evaluateNow (/usr/lib/node_modules/@boostercloud/cli/node_modules/@effect-ts/system/Fiber/context.js:870:40)
[2023-03-15T14:09:29.295Z]     at /usr/lib/node_modules/@boostercloud/cli/node_modules/@effect-ts/system/Fiber/context.js:558:47
[2023-03-15T14:09:29.295Z]     at /usr/lib/node_modules/@boostercloud/cli/node_modules/@effect-ts/system/Support/Scheduler/index.js:20:22
[2023-03-15T14:09:29.295Z]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

also happened to ttsc command:

` [2023-03-15T14:23:18.964Z] sh: 1: ttsc: not found`

## Expected behavior

Booster should run the deployment and build the required resources in AWS.

## Possible Solution

The issue seems to be with not having **rimraf** or **ttsc** installed in the system. Not that familiar with node, but shouldn't they run from local binaries in `node_modules/.bin`? When I installed them globally usin `npm i -g`, the command started working.

### Environment

- Booster version: @boostercloud/cli/1.7.0 wsl-x64 node-v14.21.3
- Node/npm version: Node 14/npm 7
- OS: Windows 11 (running in WSL 2 Ubuntu-22.04)

**Comment by ShyanRoyChoudhury** [comment]
Hi. Would love to fix this. Can I get it assigned to me?

**Comment by BatatiDE** [comment]
.take
