### ISSUE TITLE
[CLI] help display for boost sometimes shows an error

### ISSUE THREAD

**Issue by glammers1** [boostercloud/booster#196]
Example of command without errors:

```
$ boost -h            
CLI of the Booster Cloud Framework, the next level of abstraction for cloud-native applications

VERSION
  @boostercloud/cli/0.4.1 darwin-x64 node-v12.16.3

USAGE
  $ boost [COMMAND]

COMMANDS
  deploy  Deploy the current application as configured in your `index.ts` file.
  help    display help for boost
  new     generate new resource, write 'boost new' to see options
  nuke    Remove all resources used by the current application as configured in your `index.ts` file.
  run     Run the current application locally, as configured in your configuration files.
```

Example of a command with errors:

```
$ boost new:command -h
generate new resource, write 'boost new' to see options

USAGE
  $ boost new:command [COMMANDNAME]

OPTIONS
  -f, --fields=fields  field that this command will contain
  -h, --help           show CLI help

ExitError: EEXIT: 0
    at Object.exit (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/node_modules/@oclif/errors/lib/index.js:18:11)
    at Command.exit (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/command.js:54:23)
    at Command._help (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/command.js:127:21)
    at Object.parse (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/flags.js:37:17)
    at Parser._flags (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/node_modules/@oclif/parser/lib/parse.js:149:42)
    at Parser.parse (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/node_modules/@oclif/parser/lib/parse.js:117:28)
    at Object.parse (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/node_modules/@oclif/parser/lib/index.js:27:27)
    at Command.parse (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/node_modules/@oclif/command/lib/command.js:86:41)
    at Command.runWithErrors (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/dist/commands/new/command.js:16:38)
    at Command.run (/Users/glammers/.nvm/versions/node/v12.16.3/lib/node_modules/@boostercloud/cli/dist/commands/new/command.js:13:21) {
  oclif: { exit: 0 },
  code: 'EEXIT'
}
```

**Comment by juanjoman** [comment]
This looks like an `oclif` bug, which is the library we are using for CLI handling. I've opened an issue on their repository: https://github.com/oclif/oclif/issues/427

**Comment by NickSeagull** [comment]
Tried with the latest version and it doesn't happen anymore, closing unless someone reports again.
