### ISSUE TITLE
Local Provider: Event handlers

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#316]
The current local provider implementation is based on ,ExpressJS, and the local document database ,nedb,.,Implement event handlers and make sure that the resulting events are stored in the event store, implementing the corresponding required methods from the ,ProviderInterface,.,Acceptance criteria:

**Comment by juanjoman** [comment]
The necessary methods from the event-adapter are already developed:
**index.ts:** https://github.com/boostercloud/booster/blob/master/packages/framework-provider-local/src/index.ts#L24
**events-adapter:** https://github.com/boostercloud/booster/blob/master/packages/framework-provider-local/src/library/events-adapter.ts
**events-registry (db operations):** https://github.com/boostercloud/booster/blob/master/packages/framework-provider-local/src/services/event-registry.ts

Also, events are already getting stored when calling commands:
![image](https://user-images.githubusercontent.com/7570085/92883969-b1090080-f411-11ea-948e-88644fcebb7c.png)

There is currently one error when triggering commands:
```
 [BoosterEventDispatcher#dispatch] Unhandled error while dispatching event:  TypeError: this.provider.readModels.fetch is not a function
    at ReadModelStore.fetchReadModel (/Users/Juanjo/Documents/theam/public/booster/packages/framework-core/dist/services/read-model-store.js:31:41)
    at /Users/Juanjo/Documents/theam/public/booster/packages/framework-core/dist/services/read-model-store.js:22:42
    at Array.map (<anonymous>)
    at ReadModelStore.project (/Users/Juanjo/Documents/theam/public/booster/packages/framework-core/dist/services/read-model-store.js:18:39)
    at Function.snapshotAndUpdateReadModels (/Users/Juanjo/Documents/theam/public/booster/packages/framework-core/dist/booster-event-dispatcher.js:48:34)
    at async Promise.all (index 0)
    at async /Users/Juanjo/Documents/theam/public/booster/packages/framework-core/dist/booster-event-dispatcher.js:33:21
    at async Function.streamEvents (/Users/Juanjo/Documents/theam/public/booster/packages/framework-core/dist/services/raw-events-parser.js:7:13)
    at async Function.dispatch (/Users/Juanjo/Documents/theam/public/booster/packages/framework-core/dist/booster-event-dispatcher.js:21:13)
    at async storeEvents (/Users/Juanjo/Documents/theam/public/booster/packages/framework-provider-local/dist/library/events-adapter.js:44:5)
```

But this is related to #317. Notice that we are still missing the read model methods. You can check it out on the `index.ts` URL above.

Closing this. cc @itrion
