### ISSUE TITLE
Running tests on the packages?

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#349]
Submitted by @MarcAstr0 on Spectrum

> I'm trying to run the tests for the framework-provider-aws package with npm test but I get:

```
mario@MacBook-Pro-de-Mario framework-provider-aws % npm test
> @boostercloud/framework-provider-aws@0.3.1 test /Users/mario/Code/theam/booster/packages/framework-provider-aws
> nyc --extension .ts mocha --forbid-only "test/**/*.test.ts"
sh: nyc: command not found
npm ERR! Test failed.  See above for more details.
```

> I then noticed that there are very few dependencies in the package.json file (nyc not being one of them). What is the method for running the tests in the packages?

**Comment by NickSeagull** [comment]
Response by @alvaroloes 

> Have you run lerna bootstrap ? This command will install all the needed dependencies and link the packages so that everything is found. You can also run npm install.
After that, if you run npm test it should work...

**Comment by NickSeagull** [comment]
Response by @MarcAstr0 

> Turns out I wasn't using lerna at all, like a total n00b. Once I got lerna working I got the following error with the tests:

```
mario@MacBook-Pro-de-Mario booster % lerna exec -- npm test
info cli using local version of lerna
lerna notice cli v3.20.2
lerna info Executing command in 8 packages: "npm test"
> @boostercloud/framework-types@0.3.1 test /Users/mario/Code/theam/booster/packages/framework-types
> nyc --extension .ts mocha --forbid-only "test/**/*.test.ts"
TSError: ⨯ Unable to compile TypeScript:
test/config.test.ts:2:21 - error TS2307: Cannot find module 'fast-check'.
2 import * as fc from 'fast-check'
                      ~~~~~~~~~~~~
test/config.test.ts:4:24 - error TS2307: Cannot find module 'fancy-test'.
4 import { expect } from 'fancy-test'
                         ~~~~~~~~~~~~
test/config.test.ts:18:40 - error TS7006: Parameter 'appName' implicitly has an 'any' type.
18         fc.property(fc.string(1, 10), (appName) => {
                                          ~~~~~~~
test/config.test.ts:28:40 - error TS7006: Parameter 'appName' implicitly has an 'any' type.
28         fc.property(fc.string(1, 10), (appName) => {
                                          ~~~~~~~
test/config.test.ts:38:40 - error TS7006: Parameter 'appName' implicitly has an 'any' type.
38         fc.property(fc.string(1, 10), (appName) => {
                                          ~~~~~~~
test/config.test.ts:48:58 - error TS7006: Parameter 'appName' implicitly has an 'any' type.
48         fc.property(fc.string(1, 10), fc.string(1, 10), (appName, readModelName) => {
                                                            ~~~~~~~
test/config.test.ts:48:67 - error TS7006: Parameter 'readModelName' implicitly has an 'any' type.
48         fc.property(fc.string(1, 10), fc.string(1, 10), (appName, readModelName) => {
                                                                     ~~~~~~~~~~~~~
    at createTSError (/Users/mario/Code/theam/booster/node_modules/ts-node/src/index.ts:423:12)
    at reportTSError (/Users/mario/Code/theam/booster/node_modules/ts-node/src/index.ts:427:19)
    at getOutput (/Users/mario/Code/theam/booster/node_modules/ts-node/src/index.ts:554:36)
    at Object.compile (/Users/mario/Code/theam/booster/node_modules/ts-node/src/index.ts:760:32)
    at Module.m._compile (/Users/mario/Code/theam/booster/node_modules/ts-node/src/index.ts:839:43)
    at module.exports (/Users/mario/Code/theam/booster/node_modules/default-require-extensions/js.js:7:9)
    at /Users/mario/Code/theam/booster/node_modules/append-transform/index.js:64:4
    at require.extensions.(anonymous function) (/Users/mario/Code/theam/booster/node_modules/ts-node/src/index.ts:842:12)
    at Object.<anonymous> (/Users/mario/Code/theam/booster/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /Users/mario/Code/theam/booster/node_modules/mocha/lib/mocha.js:314:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/mario/Code/theam/booster/node_modules/mocha/lib/mocha.js:311:14)
    at /Users/mario/Code/theam/booster/node_modules/mocha/lib/mocha.js:347:12
    at new Promise (<anonymous>)
    at Mocha.loadFilesAsync (/Users/mario/Code/theam/booster/node_modules/mocha/lib/mocha.js:346:12)
    at singleRun (/Users/mario/Code/theam/booster/node_modules/mocha/lib/cli/run-helpers.js:107:15)
    at exports.runMocha (/Users/mario/Code/theam/booster/node_modules/mocha/lib/cli/run-helpers.js:144:11)
    at Object.exports.handler (/Users/mario/Code/theam/booster/node_modules/mocha/lib/cli/run.js:306:11)
    at Object.runCommand (/Users/mario/Code/theam/booster/node_modules/mocha/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/mario/Code/theam/booster/node_modules/mocha/node_modules/yargs/yargs.js:1096:28)
    at Object.parse (/Users/mario/Code/theam/booster/node_modules/mocha/node_modules/yargs/yargs.js:575:25)
    at Object.exports.main (/Users/mario/Code/theam/booster/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/mario/Code/theam/booster/node_modules/mocha/bin/mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (/Users/mario/Code/theam/booster/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.<anonymous> (/Users/mario/Code/theam/booster/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
npm ERR! Test failed.  See above for more details.
lerna ERR! npm test exited 1 in '@boostercloud/framework-types'
lerna ERR! npm test exited 1 in '@boostercloud/framework-types'
```

**Comment by NickSeagull** [comment]
Response by @alvaroloes 

> Ok, I see what is happening: when you test a package, nyc will interpret the Typescript code of that package, but not its dependent packages, so you need to compile them first
Try to run this:

```
lerna run compile
npm test # you don't need to wrap this in "lerna exec". It should work like this
```

**Comment by NickSeagull** [comment]
Response by @MarcAstr0 

> lerna run compile gives another error :(

```
mario@MacBook-Pro-de-Mario booster % lerna run compile
info cli using local version of lerna
lerna notice cli v3.20.2
lerna info Executing command in 8 packages: "yarn run compile"
lerna ERR! yarn run compile exited 1 in '@boostercloud/framework-types'
lerna ERR! yarn run compile stdout:
yarn run v1.22.4
$ tsc -b tsconfig.json
src/concepts/uuid.ts(1,23): error TS7016: Could not find a declaration file for module 'uuid/v4'. '/Users/mario/Code/theam/booster/node_modules/uuid/v4.js' implicitly has an 'any' type.
  Try `npm install @types/uuid` if it exists or add a new declaration (.d.ts) file containing `declare module 'uuid/v4';`
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run compile stderr:
error Command failed with exit code 1.
lerna ERR! yarn run compile exited 1 in '@boostercloud/framework-types'
```

**Comment by NickSeagull** [comment]
Response by @MarcAstr0 

> Never mind... I did lerna bootstrap and then lerna run compile and it works. Thanks for the help
