### ISSUE TITLE
Fix tests on Windows

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#538]
Currently tests fail on Windows, and although they do work on WSL, it would be interesting to fix them on Windows

**Comment by nicolatl** [comment]
Was seeing tests fail after #6 with this error:

```
$ cd packages\framework-provider-local
$ npm rushx test

> @boostercloud/framework-provider-local@1.3.0 test
> BOOSTER_ENV=test nyc --extension .ts mocha --forbid-only "test/**/*.test.ts"

'BOOSTER_ENV' is not recognized as an internal or external command,
operable program or batch file.
```

Made edits to get past this with Windows-style env var setting on my fork here: https://github.com/boostercloud/booster/commit/608df716d4144ed593861e8b64d84151321bb1b5

Now able to pass more tests, with this output:

`$ rush test


Rush Multi-Project Build Tool 5.76.1 - https://rushjs.io
Node.js version is 16.17.0 (LTS)


Starting "rush test"

Analyzing repo state... DONE (0.26 seconds)

Executing a maximum of 7 simultaneous processes...

==[ @boostercloud/eslint-config ]=================================[ 1 of 16 ]==
"@boostercloud/eslint-config" did not define any work.

==[ @boostercloud/metadata-booster ]==============================[ 2 of 16 ]==
"@boostercloud/metadata-booster" completed successfully in 4.88 seconds.

==[ @boostercloud/framework-types ]===============================[ 3 of 16 ]==
"@boostercloud/framework-types" completed successfully in 4.40 seconds.

==[ @boostercloud/framework-common-helpers ]======================[ 4 of 16 ]==
"@boostercloud/framework-common-helpers" completed successfully in 4.45 seconds.

==[ @boostercloud/application-tester ]============================[ 5 of 16 ]==
"@boostercloud/application-tester" did not define any work.       

==[ @boostercloud/framework-provider-azure ]======================[ 6 of 16 ]==
"@boostercloud/framework-provider-azure" completed successfully in 10.52 seconds.

==[ @boostercloud/framework-provider-kubernetes ]=================[ 7 of 16 ]==
"@boostercloud/framework-provider-kubernetes" completed successfully in 4.65 seconds.

==[ @boostercloud/framework-provider-kubernetes-infrastructure ]==[ 8 of 16 ]==
"@boostercloud/framework-provider-kubernetes-infrastructure" completed successfully in 28.47 seconds.

==[ @boostercloud/framework-provider-local ]=====================[
 12 of 16 ]==
"@boostercloud/framework-provider-local" completed successfully in 11.88 seconds.

==[ @boostercloud/framework-provider-aws ]=======================[
 13 of 16 ]==
"@boostercloud/framework-provider-aws" completed successfully in 18.26 seconds.

==[ @boostercloud/framework-provider-local-infrastructure ]======[
 14 of 16 ]==
"@boostercloud/framework-provider-local-infrastructure" completed successfully in 6.80 seconds.

==[ @boostercloud/framework-core ]===============================[
 15 of 16 ]==
Returned error code: 1
"@boostercloud/framework-core" failed to build.
"@boostercloud/cli" is blocked by "@boostercloud/framework-core". 
"@boostercloud/framework-integration-tests" is blocked by "@boostercloud/framework-core".
"@boostercloud/framework-provider-azure-infrastructure" is blocked by "@boostercloud/framework-core".

==[ @boostercloud/framework-provider-aws-infrastructure ]========[
 16 of 16 ]==`

Specific error log of framework-core test now:

`$ cd packages\framework-core
$ rushx test                                                                

Found configuration in C:\Users\lawfo\Documents\ECE444\oss\booster\rush.json

Rush Multi-Project Build Tool 5.76.1 - Node.js 16.17.0 (LTS)
> "set BOOSTER_ENV=test & nyc --extension .ts mocha --forbid-only \"test/**/*.test.ts\" 2>&1"


Error: Booster environment is missing. You need to provide an environment to configure your Booster project
    at checkAndGetCurrentEnv (C:\Users\lawfo\Documents\ECE444\oss\booster\packages\framework-core\src\booster.ts:49:82)
    at Object.<anonymous> (C:\Users\lawfo\Documents\ECE444\oss\booster\packages\framework-core\src\booster.ts:49:82)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)      
    at Module.replacementCompile (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\append-transform@2.0.0\node_modules\append-transform\index.js:60:13)
    at Module.m._compile (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\ts-node@10.9.1_t4lrjbt3sxauai4t5o275zsepa\node_modules\ts-node\src\index.ts:1618:23)
    at module.exports (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\default-require-extensions@3.0.1\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\append-transform@2.0.0\node_modules\append-transform\index.js:64:4
    at require.extensions.<computed> (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\ts-node@10.9.1_t4lrjbt3sxauai4t5o275zsepa\node_modules\ts-node\src\index.ts:1621:12)
    at Object.<anonymous> (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\append-transform@2.0.0\node_modules\append-transform\index.js:64:4)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) 
    at Module.require (node:internal/modules/cjs/loader:1028:19)       
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\lawfo\Documents\ECE444\oss\booster\packages\framework-core\test\booster-command-dispatcher.test.ts:3:1)   
    at Module._compile (node:internal/modules/cjs/loader:1126:14)      
    at Module.replacementCompile (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\append-transform@2.0.0\node_modules\append-transform\index.js:60:13)
    at Module.m._compile (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\ts-node@10.9.1_t4lrjbt3sxauai4t5o275zsepa\node_modules\ts-node\src\index.ts:1618:23)
    at module.exports (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\default-require-extensions@3.0.1\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\append-transform@2.0.0\node_modules\append-transform\index.js:64:4
    at require.extensions.<computed> (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\ts-node@10.9.1_t4lrjbt3sxauai4t5o275zsepa\node_modules\ts-node\src\index.ts:1621:12)
    at Object.<anonymous> (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\append-transform@2.0.0\node_modules\append-transform\index.js:64:4)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) 
    at Module.require (node:internal/modules/cjs/loader:1028:19)       
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\mocha@8.4.0\node_modules\mocha\lib\esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\mocha@8.4.0\node_modules\mocha\lib\esm-utils.js:55:34)
    at async singleRun (C:\Users\lawfo\Documents\ECE444\oss\booster\common\temp\node_modules\.pnpm\mocha@8.4.0\node_modules\mocha\lib\cli\run-helpers.js:125:3)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |   18.23 |     0.29 |    0.34 |   14.35 |                   
 src      |   17.79 |      0.8 |    0.73 |   14.58 |                   
  ...r.ts |   36.36 |        0 |       0 |      25 | 5-21              
  ...r.ts |   25.71 |        0 |       0 |   21.87 | 19-66             
  ...r.ts |   21.27 |        0 |       0 |   18.18 | 24-105            
  ...r.ts |   17.64 |        0 |       0 |    12.5 | 16-81             
  ...r.ts |    8.33 |        0 |       0 |    6.25 | 17-108            
  ...r.ts |   14.13 |        0 |       0 |   12.22 | 28-229            
  ...r.ts |    12.5 |        0 |       0 |    9.83 | 19-161            
  ...r.ts |   34.78 |        0 |       0 |   28.57 | 24-74             
  ...r.ts |   33.33 |        0 |       0 |      20 | 4-19              
  ...r.ts |   23.33 |        0 |       0 |   18.51 | 16-53             
  ...r.ts |   13.55 |        0 |       0 |   10.71 | 21-128            
  ...r.ts |   15.15 |        0 |       0 |      12 | 11-56             
  ...r.ts |   23.45 |    11.76 |       4 |   24.05 | 50-232,246-266    
  ...r.ts |    23.8 |        0 |       0 |   15.78 | 6-50              
  ...r.ts |    12.5 |        0 |       0 |     8.1 | 10-96             
  ...r.ts |   13.15 |        0 |       0 |    8.57 | 17-92             
 ...ities |   44.44 |      100 |       0 |      40 |                   
  ...y.ts |   44.44 |      100 |       0 |      40 | 6-19              
 ...vents |      45 |        0 |       0 |   21.42 |                   
  ...d.ts |      50 |        0 |       0 |      25 | 6-11              
  ...d.ts |      50 |        0 |       0 |      25 | 6-11              
  ...d.ts |    37.5 |      100 |       0 |   16.66 | 5-12              
 ...ators |   16.66 |        0 |       0 |   18.18 |                   
  ...a.ts |   16.66 |        0 |       0 |   18.18 | 6-10,27-40        
 ...vices |      12 |        0 |       0 |     8.6 |                   
  ...e.ts |    8.73 |        0 |       0 |    7.29 | 18-205            
  ...s.ts |   33.33 |      100 |       0 |      20 | 15-19,27-31       
  ...r.ts |      25 |        0 |       0 |   14.28 | 18-45             
  ...e.ts |   10.14 |        0 |       0 |    7.57 | 19-180            
 ...aphql |   19.23 |        0 |       0 |   16.19 |                   
  ...n.ts |   36.84 |        0 |       0 |   35.29 | 52-63,68,72-76    
  ...r.ts |   21.66 |        0 |       0 |   18.96 | 35-216            
  ...r.ts |   12.12 |        0 |       0 |    6.89 | 8-73              
  ...r.ts |   33.33 |        0 |       0 |   27.27 | 17-51             
  ...r.ts |      20 |        0 |       0 |   14.28 | 12-64             
  ...r.ts |   10.29 |        0 |       0 |    8.92 | 22-130            
 ...ators |   32.43 |        0 |       0 |   24.24 |                   
  ...r.ts |      20 |        0 |       0 |   11.11 | 8-44              
  ...r.ts |      50 |      100 |       0 |      40 | 18-55             
  ...r.ts |    37.5 |        0 |       0 |   28.57 | 12-31             
  ...r.ts |   30.76 |        0 |       0 |      25 | 24-76             
 ...lpers |   14.39 |        0 |       0 |    11.4 |                   
  ...r.ts |   10.25 |        0 |       0 |    8.45 | 22-174            
  ...r.ts |   41.66 |        0 |       0 |      30 | 10-31             
  ...r.ts |   14.28 |        0 |       0 |   12.12 | 10-58             
 ...tocol |    7.04 |        0 |       0 |    4.34 |                   
  ...l.ts |    7.04 |        0 |       0 |    4.34 | 33-175            
 ...b-sub |   13.63 |        0 |       0 |     9.8 |                   
  ...b.ts |      80 |      100 |       0 |   66.66 | 9                 
  ...b.ts |    8.19 |        0 |       0 |    6.25 | 21-121            
 ...fiers |   35.38 |        0 |       0 |   29.82 |                   
  ...x.ts |     100 |      100 |     100 |     100 |                   
  ...r.ts |      50 |      100 |       0 |   44.44 | 17-24             
  ...r.ts |      50 |      100 |       0 |   42.85 | 6-12              
  ...r.ts |   23.52 |        0 |       0 |   13.33 | 6-14,19-28        
  ...s.ts |   18.18 |        0 |       0 |   18.18 | 13-14,31-40,58-76 
----------|---------|----------|---------|---------|-------------------
The script failed with exit code 1`

Please let me know if you have any direction with respect to setting up my Booster environment.
