### ISSUE TITLE
Access denied while doing Booster.readModel

### ISSUE THREAD

**Issue by carlosper88** [boostercloud/booster#829]
# Bug Report

## Current Behavior

I got this weird error while doing Booster.readModel inside another readModel projection. The code is this

```
  @Projects(Creator, 'id')
  public static projectCreator(entity: Creator): ProjectionResult<CreatorReadModel> {
    const socialAccounts = Booster.readModel(SocialAccount)
      .filter({ creatorId: { eq: entity.id } })
      .search()
      .then((readmodels) => {
        return readmodels
      })
    const stringSocialAccounts = socialAccounts ? JSON.stringify(socialAccounts) : ''
    return {
      id: entity.id,
      name: entity.name,
      image: entity.image,
      description: entity.description,
      socialAccounts: stringSocialAccounts,
    }
  }
```

The error I'm getting on Cloudwatch is this one:

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "AccessDeniedException: User: arn:aws:sts::944382000204:assumed-role/counteract-bk-dev-app-eventsmainServiceRoleF88A741-18CVLA6NI66RX/counteract-bk-dev-app-events-main is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:944382000204:table/counteract-bk-dev-app-SocialAccount",
    "reason": {
        "errorType": "AccessDeniedException",
        "errorMessage": "User: arn:aws:sts::944382000204:assumed-role/counteract-bk-dev-app-eventsmainServiceRoleF88A741-18CVLA6NI66RX/counteract-bk-dev-app-events-main is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:944382000204:table/counteract-bk-dev-app-SocialAccount",
        "code": "AccessDeniedException",
        "message": "User: arn:aws:sts::944382000204:assumed-role/counteract-bk-dev-app-eventsmainServiceRoleF88A741-18CVLA6NI66RX/counteract-bk-dev-app-events-main is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:944382000204:table/counteract-bk-dev-app-SocialAccount",
        "time": "2021-05-11T14:00:28.157Z",
        "requestId": "M9KHE9RHSPO3QS301JFRNHDDKBVV4KQNSO5AEMVJF66Q9ASUAAJG",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 20.956427602213513,
        "stack": [
            "AccessDeniedException: User: arn:aws:sts::944382000204:assumed-role/counteract-bk-dev-app-eventsmainServiceRoleF88A741-18CVLA6NI66RX/counteract-bk-dev-app-events-main is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:944382000204:table/counteract-bk-dev-app-SocialAccount",
            "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
            "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: AccessDeniedException: User: arn:aws:sts::944382000204:assumed-role/counteract-bk-dev-app-eventsmainServiceRoleF88A741-18CVLA6NI66RX/counteract-bk-dev-app-events-main is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:944382000204:table/counteract-bk-dev-app-SocialAccount",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

It seems to be a permissions issue, but that `SocialAccountReadModel` I'm trying to read has an authorization header of 'all', so it wouldn't be a problem.
The code continues executing and returning the `CreatorReadModel` with `{}` on the `socialAccounts` field

## Expected behavior

If I do a `SocialAccountReadModel` request, I'm able to see some results. So the expected behavior is not to have the access error and the content inside the `CreatorReadModel`

### Environment

- Booster version: 0.14.6
- Node/npm version: Node v14.2, npm v6.14.5
- OS: OSX 10.15.7

**Comment by javiertoledo** [comment]
This looks like a permission missing error in the event handler lambdas. Accessing a read model from an event handler is not a good idea because Read Models doesn't guarantee consistency, but we don't have a better way to make complex queries to data yet. As a workaround, could you use the GraphQL API from the event handler to make the query?

**Comment by juanjoman** [comment]
Hey @carlosper88 I just researched this and it's currently working. What's happening is that `Booster.readModels()` should receive a read-model as a parameter, and not an entity. This is the code you shared:

```typescript
const socialAccounts = Booster.readModel(SocialAccount) <<<<----- This is an entity
      .filter({ creatorId: { eq: entity.id } })
      .search()
      .then((readmodels) => {
        return readmodels
      })
```

It should be:
```typescript
const socialAccounts = Booster.readModel(SocialAccountReadModel) <<<<-------- We pass a read model
      .filter({ creatorId: { eq: entity.id } })
      .search()
      .then((readmodels) => {
        return readmodels
      })
```

I just checked it on event-handlers, can you try again?

**Comment by carlosper88** [comment]
Hey @juanjoman I double checked this and it's working perfectly. Thanks for taking a look
