### ISSUE TITLE
Allow commands with no fields

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#893]
# Bug Report

## Current Behavior

If a command with no fields is defined, the `graphql-handler` lambda will fail complaining about that it has no fields:

```text
Error: Input Object type StartReviewInput must define one or more fields.
    at assertValidSchema (/var/task/node_modules/graphql/type/validate.js:69:11)
    at Object.validate (/var/task/node_modules/graphql/validation/validate.js:51:35)
    at BoosterGraphQLDispatcher.runGraphQLOperation (/var/task/node_modules/@boostercloud/framework-core/dist/booster-graphql-dispatcher.js:79:36)
    at BoosterGraphQLDispatcher.handleMessage (/var/task/node_modules/@boostercloud/framework-core/dist/booster-graphql-dispatcher.js:64:21)
    at async BoosterGraphQLDispatcher.dispatch (/var/task/node_modules/@boostercloud/framework-core/dist/booster-graphql-dispatcher.js:33:66)
```

## Expected behavior

I can define commands with no fields

## Possible Solution

Generate a command with an optional field that's ignored?

### Environment

@boostercloud/cli/0.17.0 darwin-x64 node-v14.17.0

**Comment by javiertoledo** [comment]
This issue is solved by https://github.com/boostercloud/booster/pull/1021
