### ISSUE TITLE
[CLI] Remove stack trace from CLI's stdout messages

### ISSUE THREAD

**Issue by glammers1** [boostercloud/booster#94]
**Environment**

`@boostercloud/cli/0.3.3 darwin-x64 node-v12.16.3`

**Steps to reproduce it:**

You just need to generate an error executing a CLI command, for instance, having on purpose a wrong AWS credentials configuration.

**Expected result**

Stack trace could be removed from those messages because it doesn't help much the user. In fact, in previous versions like 0.2.1, there was no stack trace:

```
$ boost deploy -e production
ℹ boost deploy [production] 🚀
ℹ Bootstrapping the following environment: {"name":"Default environment","account":"155431809731","region":"us-east-1"}
✖ The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (You can see the full error logs in ./errors.log)
```

**Result**

```
$ boost deploy -e production
ℹ boost deploy [production] 🚀
ℹ Bootstraping the following environment: {"name":"Default environment","account":"155431809731","region":"us-east-1"}
✖ SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
    at Request.extractError (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/glammers/development/theam/my-first-booster-project/node_modules/@boostercloud/framework-provider-aws-infrastructure/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Comment by MYF95** [comment]
It seems this was added consciously in https://github.com/boostercloud/booster/commit/5aa1d7d7f058703c4d092441c8e7a3e6a6f27d65

I know @NickSeagull mentioned the user should not see the stack trace, but given it was committed fairly recently, might this be intended after all?

**Comment by glammers1** [comment]
Good call @MYF95. @itrion suggested removing the stack trace but allow the user to see the complete log somehow. Something similar to NPM may work:

```
$ npm run lorem
npm ERR! missing script: lorem

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/glammers/.npm/_logs/2020-05-26T10_46_36_172Z-debug.log
```

NPM takes advantage of its `.npm` folder. In our case, we could use our `.booster` folder, which is already ignored in the generated `.gitignore`. 

Anyways, as per @alvaroloes pointed out, stack traces are important for users to ask questions in Spectrum or create issues providing as much information as possible. We should leave them accessible.

Since you introduced the change @javiertoledo, what do you think?

**Comment by javiertoledo** [comment]
Generally, I'd rather see a stack trace with as many details about what happened as possible because it helps to troubleshoot issues.

**Comment by NickSeagull** [comment]
As an end user of a command line tool? For me it is not very desirable, unless the user specifies `--verbose` or something

**Comment by javiertoledo** [comment]
I guess this is a matter of taste, and I see that most of you prefer to avoid seeing the whole stack trace. Let's do it as @glammers1 suggested: dump the stack trace to a file and say something like "this failed, you can find the full stack trace in ./errors.log". We can have the `--verbose` flag too, but it can't be the only option. There are some situations where running the command again with `--verbose` would not be the best idea (for instance, when a very long deploy fails, or when the error have produced some side effect that you don't want to repeat)

**Comment by javiertoledo** [comment]
I've edited the issue description to show a `(You can see the full error logs in ./errors.log)` string after the error message.
